name: Integration tests

on:
  push:
    branches:
      - master
      - main
      - v1.0-dev
    paths:
      - "Gemfile"
      - "_config.yml"
      - "_includes/**"
      - "_layouts/**"
      - "test/**"
      - ".github/workflows/unit-tests.yml"
  pull_request:
    branches:
      - master
      - main
      - v1.0-dev
    paths:
      - "Gemfile"
      - "_config.yml"
      - "_includes/**"
      - "_layouts/**"
      - "test/**"
      - ".github/workflows/unit-tests.yml"

jobs:
  comments-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Run comments integration test ğŸ§ª
        run: bash test/integration_comments.sh
